services:
  mysql:
    image: mysql
    container_name: multiple_datasources-mysql
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: "mysql"
    ports:
      - "3306:3306"
  postgres:
    image: postgres
    container_name: multiple_datasources-postgres
    environment:
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "postgres"
    ports:
      - "5432:5432"